#!/usr/bin/env ruby

# This script was inspired by one written by Erik Kastner, 
# and a blog describing it's needs and usage can be found at 
# http://metaatem.net/2007/04/20/fun-with-active_record-and-sqlite3
# 
# It can be used for hands on quick and dirty testing to see how the library 
# is working in the IRB console. 
#
# This file must be executable to work: [sudo] chmod 775 spec/console
#

require 'rubygems'
require 'irb'

$:.unshift(File.dirname(__FILE__) + '/../../flix4r' )
require 'flix4r' # for comparison

$:.unshift(File.dirname(__FILE__) + '/../lib')

RAILS_ROOT = File.join( File.dirname(__FILE__), '..' )
require 'netflix_dogs' 

# load real netflix credentials to test how it really works
NetflixDogs::Requester.config_location = RAILS_ROOT + '/config/real_netflix.yml' 

# load also an xml file with Nokogiri 
DATA =  File.join( File.dirname(__FILE__), '/data' )
@xml = File.open( "#{DATA}/catalog/title_search.xml", 'r' ).read
@parser = Nokogiri.XML(@xml) 

# start the conole with these variables
IRB.start if __FILE__ == $0     